name: Generate Book Formats

on:
  push:
    branches:
      - main

jobs:
  generate_formats:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive texlive-xetex

      - name: Create directories
        run: |
          mkdir -p generated/html
          mkdir -p generated/epub
          mkdir -p generated/pdf

      - name: Combine Markdown files
        run: |
          cat chapters/*.md > combined.md

      # - name: Generate HTML
      #   run: |
      #     pandoc combined.md -o generated/html/book.html

      - name: Generate EPUB
        run: |
          pandoc combined.md -o generated/epub/book.epub

      - name: Generate PDF
        run: |
          pandoc combined.md -o generated/pdf/book.pdf

      - name: Upload generated files
        uses: actions/upload-artifact@v2
        with:
          name: book-formats
          path: |
            generated/